.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MASALA" "1" "February 2013" "" ""
.
.SH "NAME"
\fBmasala\fR \- P2P name resolution daemon
.
.SH "SYNOPSIS"
\fBmasala\fR [\-d] [\-q] [\-h hostname] [\-k password] [\-p port] [\-x server] [\-y port] [\-u username]
.
.SH "DESCRIPTION"
\fBmasala\fR is a P2P name resolution daemon\. It organizes IPv6 addresses in a distributed hash table\. The basic design has been inspired by the Kademlia DHT\. The communication between nodes is realized by using bencode encoded messages on top of UDP\. There are 4 message types: PING, FIND, LOOKUP and ANNOUNCE\. It is possible to encrypt the traffic with a PSK to isolate your nodes from a bigger swarm\. By default, masala sends the first packet to a multicast address\. So, there is no configuration necessary within your broadcast domain (LAN)\. With a bootstrap server, it is also possible to connect nodes around the globe\. A NSS module makes any hostname with \fI\.p2p\fR at the end transparently available to your Linux OS\.
.
.SH "FILES"
.
.TP
\fB/etc/nsswitch\.conf\fR
masala gets attached to the \fIhosts\fR line\. The masala daemon is used to lookup an IPv6 address if the requested hostname ends on \fI\.p2p\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR \fIhostname\fR
By default /etc/hostname is used to determine the hostname\.
.
.TP
\fB\-k\fR \fIpassword\fR
Setting a password results in encrypting each packet with AES256\. The encrypted packet is encapsulated in bencode\.
.
.TP
\fB\-p\fR \fIport\fR
Listen to this port (Default: UDP/8337)
.
.TP
\fB\-x\fR \fIserver\fR
Use server as a bootstrap server\. The server can be an IPv6 address, a FQHN like www\.example\.net or even a IPv6 multicast address\. (Default: ff0e::1)
.
.TP
\fB\-y\fR \fIport\fR
The bootstrap server will be addressed at this port\. (Default: UDP/8337)
.
.TP
\fB\-u\fR \fIusername\fR
When starting as root, use \-u to change the UID\.
.
.TP
\fB\-d\fR
Start as a daemon and run in background\. The output will be send to syslog\.
.
.TP
\fB\-q\fR
Be quiet and do not log anything\.
.
.SH "EXAMPLES"
Announce the hostname \fIfubar\.p2p\fR with the encryption password \fIfubar\fR:
.
.IP "" 4
.
.nf

$ masala \-h fubar\.p2p \-k fubar
.
.fi
.
.IP "" 0
.
.SH "BUGS"
Lack of IPv6 support by the providers\.
.
.SH "SEE ALSO"
nsswitch\.conf(5)
