.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TORRENTKINO" "1" "December 2017" "" ""
.
.SH "NAME"
\fBtorrentkino\fR \- Kademlia DHT
.
.SH "SYNOPSIS"
\fBtk[46]\fR [\-p port] [\-r realm] [\-d port] [\-a port] [\-x server] [\-y port] [\-q] [\-l] [\-s] hostname
.
.SH "DESCRIPTION"
\fBTorrentkino\fR is a Bittorrent DNS resolver\. All DNS queries to Torrentkino get translated into SHA1 hashes and are getting resolved by looking these up in a Kademlia distributed hash table\. It is fully compatible to the DHT as used in most Bittorrent clients\. The swarm becomes the DNS backend for Torrentkino\.
.
.P
By default, Torrentkino sends the first packet to a multicast address\. So, for intranet use cases, you do not need a Bittorrent bootstrap server\. Just start Torrentkino on 2 nodes without any parameters\. It simply works\.
.
.P
If you would like to connect nodes around the globe, you may use the Bittorrent network\. Simply select a Bittorrent bootstrap server as seen in the example below\. Your client becomes a full member of the swarm and resolves Bittorrent SHA1 hashes to IP/port tuples\. The swarm on the other end does the same for you\. But in your case, the SHA1 hash represents a hostname instead of a torrent file\.
.
.P
Torrentkino runs as user \fInobody\fR when started with root priviledges\.
.
.SH "OPTIONS"
.
.TP
\fB\-p\fR \fIport\fR
Listen to this port and use it for the DHT operations\. (Default: UDP/6881)
.
.TP
\fB\-P\fR \fIport\fR
Listen to this port and use it for the DNS operations\. (Default: UDP/5353)
.
.TP
\fB\-a\fR \fIport\fR
Announce this port (Default: UDP/8080)
.
.TP
\fB\-n\fR \fInode id string\fR
By default a random node id gets computed on every startup\. For testing purposes it may be useful to keep the same node id all the time\. The above string is not used directly\. Instead its SHA1 hash is used\.
.
.TP
\fB\-r\fR \fIrealm\fR
Creating a realm affects the method to compute the "SHA1" hash\. It helps you to isolate your nodes and be part of a bigger swarm at the same time\. This is useful to handle duplicate hostnames\. With different realms everybody may have his own https://nextcloud\.p2p for example\. Technically, the realm is a SHA1 hash too\. It gets merged to the hostname\'s SHA1 hash by using XOR\.
.
.TP
\fB\-x\fR \fIserver\fR
Use server as a bootstrap server\. Otherwise a multicast address is used\. For LAN only cases the multicast bootstrap is enough\.
.
.TP
\fB\-y\fR \fIport\fR
The bootstrap server will be addressed at this port\. (Default: UDP/6881)
.
.TP
\fB\-l\fR
Lazy mode: This option sets multiple predefined bootstrap server like \fIrouter\.utorrent\.com\fR for example\.
.
.TP
\fB\-d\fR
Fork and become a daemon\.
.
.TP
\fB\-q\fR
Be quiet\.
.
.SH "NSS"
Torrentkino also provides a NSS module\. Add \fItk4\fR or \fItk6\fR to your \fI/etc/nsswitch\.conf\fR file\. Hostnames with a \fI\.p2p\fR TLD will be redirected to the Torrentkino daemon\. See the examples below\.
.
.P
hosts: files tk4 dns
.
.SH "EXAMPLES"
Announce the hostnames \fInextcloud\.p2p\fR and \fI_http\._tcp\.foo\.bar\fR globally\.
.
.IP "" 4
.
.nf

$ sudo tk6 \-P 53 \-l nextcloud\.p2p _http\._tcp\.foo\.bar
$ dig AAAA nextcloud\.p2p @localhost
$ dig SRV _http\._tcp\.foo\.bar @localhost
.
.fi
.
.IP "" 0
.
.P
Announce the hostname \fImycloud\.p2p\fR within the LAN\.
.
.IP "" 4
.
.nf

$ sudo tk4 \-P 53 mycloud\.p2p
$ dig mycloud\.p2p @localhost
.
.fi
.
.IP "" 0
.
.P
Isolate your nodes within a realm \fIdarkness\fR, fork the process into background and be quiet\.
.
.IP "" 4
.
.nf

$ sudo tk6 \-r darkness \-l \-P 53 \-d \-q torrentkino\.cloud
$ dig torrentkino\.cloud @localhost
.
.fi
.
.IP "" 0
.
.P
With the NSS daemon in place, you can use the \fI\.p2p\fR system\-wide\.
.
.P
$ getent hosts nextcloud\.p2p $ ping nextcloud\.p2p $ curl nextcloud\.p2p
.
.SH "INSTALLATION"
There is a simple installation helper for Debian/Ubuntu\. Just run one of the following commands to create a installable package\.
.
.IP "" 4
.
.nf

$ make debian
$ make ubuntu
.
.fi
.
.IP "" 0
.
.P
Otherwise, you may use
.
.IP "" 4
.
.nf

$ make
$ sudo make install
.
.fi
.
.IP "" 0
.
.SH "CREDITS"
Thanks to Moritz Warning for his help with the DNS API\.
