.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TORRENTKINO" "1" "April 2014" "" ""
.
.SH "NAME"
\fBtorrentkino\fR \- Kademlia DHT
.
.SH "SYNOPSIS"
\fBtorrentkino\fR [\-v] [\-q] [\-p port] [\-a hostname] [\-g group] [\-d domain] [\-r realm] [\-s] [\-l] [\-x server] [\-y port]
.
.SH "DESCRIPTION"
\fBtorrentkino\fR is a P2P name resolution daemon\. It resolves hostnames into IP addresses by using a Kademlia distributed hash table\. This DHT is compatible to the DHT as used in Bittorrent clients like Transmission\.
.
.P
By default, torrentkino sends the first packet to a multicast address\. So, for intranet use cases, you do not need a bootstrap server\. Just start torrentkino on 2 nodes without any parameters\. It simply works\.
.
.P
If you would like to connect nodes around the globe, you may use the Bittorrent network\. Simply select a Bittorrent bootstrap server as seen in the example below\. Your client becomes a full member of the swarm and resolves info hashes to IP/port tuples\. The swarm on the other end does the same for you\. But in your case, the info hash represents a hostname instead of a torrent file\.
.
.P
A NSS module makes any hostname with a \fI\.p2p\fR TLD transparently available to your Linux OS\.
.
.SH "FILES"
.
.TP
\fB/etc/nsswitch\.conf\fR
Add \fBtk\fR to the \fIhosts\fR line and your Linux OS will forward \fI\.p2p\fR requests to the Torrentkino DHT daemon\.
.
.TP
\fB$HOME/\.torrentkino\.conf\fR
This file gets written by the Torrentkino daemon and contains the server port number and some other hints like the TLD it shall be responsible for\. Those hints are used by \fBlibnss_tk\.so\.2\fR and the \fBtk\fR cli program\.
.
.TP
\fB/etc/torrentkino\.conf\fR
This file gets written by the Torrentkino daemon when started by root for example at boot time or by using sudo\. It works like the file above\. \fBlibnss_tk\.so\.2\fR and the \fBtk\fR cli program will look for \fB$HOME/\.torrentkino\.conf\fR first\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR \fIhostname\fR
Announce this hostname\. By default /etc/hostname is used to determine your hostname\. The SHA1 hash of the hostname becomes the announced info_hash\.
.
.TP
\fB\-g\fR \fIgroup\fR
Announce this group to organize different nodes in a workgroup\. This can be used as a discovery service\. Lookup the group and you will see the other members\.
.
.TP
\fB\-d\fR \fIdomain\fR
Instead of using the default TLD \fI\.p2p\fR, you may chose a differrent TLD like \fI\.darknet\fR, \fI\.cloud\fR or \fI\.files\fR\. This setting primarely affects the NSS module, because it needs to know for what TLD it shall be responsible\.
.
.TP
\fB\-n\fR \fInode id string\fR
By default a random node id gets computed on every startup\. For testing purposes it may be useful to keep the same node id all the time\. The above string is not used directly\. Instead its SHA1 hash is used\.
.
.TP
\fB\-r\fR \fIrealm\fR
Creating a realm affects the method how to compute the info hash\. It helps you to isolate your nodes and be part of a bigger swarm at the same time\. This is useful to handle duplicate hostnames\. With different realms everybody may have his own http://mycloud\.p2p for example\.
.
.TP
\fB\-s\fR
Strict mode: In this mode all friendly nodes must operate on the same port to find each other\. Nodes, that operate/announce different ports, do not show up in search results, even if they announce the \fIright\fR SHA1 hash\.
.
.TP
\fB\-p\fR \fIport\fR
Listen to this port (Default: UDP/6881)
.
.TP
\fB\-x\fR \fIserver\fR
Use server as a bootstrap server\. Otherwise a multicast address is used\. For LAN only cases the multicast bootstrap is enough\.
.
.TP
\fB\-y\fR \fIport\fR
The bootstrap server will be addressed at this port\. (Default: UDP/6881)
.
.TP
\fB\-l\fR
Lazy mode: This option sets a predefined bootstrap server like \fIrouter\.utorrent\.com\fR for example\.
.
.TP
\fB\-f\fR
Fork a daemon and run in background\. The output will be send to syslog\.
.
.TP
\fB\-v\fR
Verbose\. Default for the console mode\.
.
.TP
\fB\-q\fR
Be quiet\. Default for the daemon mode\.
.
.SH "EXAMPLES"
Announce the hostname \fImy\.cloud\fR globally\.
.
.IP "" 4
.
.nf

$ torrentkino6 \-a my \-d cloud \-l
$ getent hosts my\.cloud
$ tk my\.cloud
$ tk http://my\.cloud/index\.html
.
.fi
.
.IP "" 0
.
.P
Announce the hostname \fImycloud\.p2p\fR within the LAN\.
.
.IP "" 4
.
.nf

$ torrentkino4 \-a mycloud
$ getent hosts mycloud\.p2p
$ tk mycloud\.p2p
$ tk http://mycloud\.p2p/index\.html
.
.fi
.
.IP "" 0
.
.P
Isolate your nodes within a realm \fIdarkness\fR, fork the process into background and log everything to syslog\.
.
.IP "" 4
.
.nf

$ torrentkino6 \-a torrentkino \-d cloud \-r darkness \-l \-s \-f \-v
$ getent hosts torrentkino\.cloud
$ tk torrentkino\.cloud
$ tk http://torrentkino\.cloud/index\.html
.
.fi
.
.IP "" 0
.
.SH "INSTALLATION"
There is a simple installation helper for Debian/Ubuntu\. Just run one of the following commands to create a installable package\.
.
.IP "" 4
.
.nf

$ make debian
$ make ubuntu
.
.fi
.
.IP "" 0
.
.P
Otherwise, you may use
.
.IP "" 4
.
.nf

$ make
$ sudo make install
.
.fi
.
.IP "" 0
.
.P
Add \fBtk\fR to the \fI/etc/nsswitch\.conf\fR\. Example:
.
.IP "" 4
.
.nf

hosts: files tk dns
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
nsswitch\.conf(5)
