.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TUMBLEWEED" "1" "November 2013" "" ""
.
.SH "NAME"
\fBtumbleweed\fR \- Instant webserver
.
.SH "SYNOPSIS"
\fBtumbleweed\fR [\-d] [\-q] [\-6] [\-w workdir] [\-p port] [\-i index]
.
.SH "DESCRIPTION"
\fBtumbleweed\fR is a simple webserver for static content with a low memory footprint for the Linux OS\. It uses the Linux EPOLL event system, does non\-blocking IO, supports Zero\-Copy and uses all the cores you have\. It is actually quite fast\. Though only a few HTTP features are supported such as HTTP Pipelining, Keep\-alive and Range Requests as seen in the wild\.
.
.SH "OPTIONS"
.
.TP
\fB\-w\fR \fIworkdir\fR
Share this directory\. (Default: ~/Public)
.
.TP
\fB\-p\fR \fIport\fR
Listen to this port\. (Default: TCP/8080)
.
.TP
\fB\-i\fR \fIindex\fR
Serve this file if the requested entity is a directory\. (Default: index\.html)
.
.TP
\fB\-d\fR
Start as a daemon and run in background\. The output will be send to syslog\.
.
.TP
\fB\-q\fR
Be quiet and do not log anything\.
.
.TP
\fB\-6\fR
IPv6 only\.
.
.SH "EXAMPLES"
Serve \fI~/Public\fR at port \fI8080\fR:
.
.IP "" 4
.
.nf

$ tumbleweed
.
.fi
.
.IP "" 0
.
.SH "BUGS"
Not being fully blown with funky features\.
